[package]
name = "raw_vulkan_handle"
description = "Rust definitions of the Vulkan \"handle\" and \"non-dispatchable handle\" types."
repository = "https://github.com/Lokathor/raw_vulkan_handle"
version = "0.1.0"
edition = "2021"
license = "Zlib OR Apache-2.0 OR MIT"
